### ISSUE TITLE
shafan/omnipay-scellius non disponible publiquement

### ISSUE THREAD

**Issue by diglin** [kfeine/Attendize#12]
Bonjour,

Je découvre votre repo et vois qu'il est plus actif que l'officiel. Du coup, je me suis dis, pourquoi ne pas utiliser celui-là plutôt et participer si besoin

Cependant à l'install via composer, j'ai un soucis avec repo qui n'est pas dispo publiquement: c'est `shafan/omnipay-scellius`. Y-a-t-il un moyen de résoudre cela ?

Merci d'avance et bonnes fêtes.

**Comment by shafan** [comment]
Bonjour diglin,
Désolé pour la réponse tardive. Omnipay-scellius n'est pour le moment pas dispo publiquement effectivement pour une question de sécurité. Je n'ai pas finit d'auditer le code. Et comme nous l'utilisons pour notre site, nous préférons pour le moment ne pas le publier.

Par contre, normalement cela ne cause aucun problème pour utiliser la repo. Il suffit de supprimer la dépendance omnipay-scellius dans composer.json

Si vous souhaitez utiliser omnipay-scellius, n'hésitez pas à me le dire que je me presse à faire cet audit :)

**Comment by diglin** [comment]
Bonjour,

Merci pour votre réponse. Non je n'en ai pas besoin, c'est juste que je voulais fournir un feedback concernant le problème pour l'installation via composer. J'ai retiré la dépendance dans composer pour pouvoir faire le reste de l'installation sans problème

Merci et bonne continuation.
