### ISSUE TITLE
Version française d'Attendize

### ISSUE THREAD

**Issue by eraviart** [kfeine/Attendize#13]
Bonjour,

Je cherche une version française d'Attendize et vous avez visiblement déjà effectué un gros travail d'internationalisation et de localisation.

Mais est-ce que votre version est dédiée à un usage particulier ou est ce qu'elle a les mêmes usages que le logiciel d'origine ?

**Comment by shafan** [comment]
Alors je répond un peu tard désolé. Globalement, c'est la même chose. Nos spécificité ont été ajouté sur la branche CAEF.
