### ISSUE TITLE
Gestion réduction/gratuité

### ISSUE THREAD

**Issue by shafan** [kfeine/Attendize#6]
Il y a bien une possibilité d'inscrire quelqu'un de façon gratuite. Il reçoit alors son ticket par mail et est noté comme finalisé (payé).

Par contre, la gestion de la réduction n'est pas incorporé. A voir comment on veut l'incorporer. Code promo ? En fonction d'une case à coché (chomeur...) ?

**Comment by kfeine** [comment]
Le but serait d’avoir la possibilité d’avoir des codes promo

**Comment by kfeine** [comment]
La fonctionnalité a été ajoutée
